language: python
python:
  - 2.7
sudo: false

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - pip install --upgrade pip;
  - pip install numpy scipy matplotlib Pillow ipywidgets properties[math] request
  - pip install SimPEG
  - pip install em_examples

# Run test
script:
  - nosetests $TEST_DIR

notifications:
  slack: ubcgif:1Z2lR3XYRSM3GHflG71ZHEN6
