name: em_examples

dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipython
  - ipywidgets
  - os
  - sys
  - pip:
    - git+git://github.com/simpeg/simpeg.git@dcip/dev
