name: em_examples

dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - ipython
  - ipywidgets
  - pip:
    # - git+git://github.com/simpeg/simpeg.git@dcip/dev
    - git+git://github.com/simpeg/simpeg.git@master
