name: em_examples

dependencies:
  - python=2.7
  - numpy
  - matplotlib
  - pandas
  - scipy
  - Pillow
  - ipywidgets
  - pip:
    - properties[math]

install:
  # - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib ipywidgets
  - git clone https://github.com/simpeg/simpeg.git
  - cd simpeg; git checkout dcip/dev; git pull; python setup.py build_ext --inplace; cd ..
  - export PATH=$PWD/simpeg:$PWD/em_examples:$PATH
  - export PYTHONPATH=$PWD/em_examples:$PYTHONPATH
